use std::fs;
use std::io;
use std::path::PathBuf;

use crate::config;
use crate::install;

const MARKER_START: &str = "# >>> tmuxxer >>>";
const MARKER_END: &str = "# <<< tmuxxer <<<";

pub fn install_ctrl_f_binding() -> io::Result<()> {
    let home = config::home_dir()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME not set"))?;
    let bashrc = home.join(".bashrc");
    let bind_script = bind_script_path();

    if let Some(parent) = bind_script.parent() {
        fs::create_dir_all(parent)?;
    }

    let tmuxxer = install::resolve_tmuxxer()?;
    let bind_script_body = format!(
        "# Generated by tmuxxer — keep sourced last from ~/.bashrc\n\
         bind -x '\"\\C-f\": \"{}\"'\n",
        tmuxxer.display()
    );
    fs::write(&bind_script, bind_script_body)?;

    let bind_script_s = bind_script.display();
    let source_line = format!("[[ -f \"{bind_script_s}\" ]] && source \"{bind_script_s}\"");
    let block = format!("{MARKER_START}\n{source_line}\n{MARKER_END}\n");

    let mut content = if bashrc.exists() {
        fs::read_to_string(&bashrc)?
    } else {
        String::from("# tmuxxer\n")
    };

    if let Some((start, end)) = find_block_span(&content) {
        content.replace_range(start..end, &block);
    } else if !content.ends_with('\n') {
        content.push('\n');
        content.push_str(&block);
    } else {
        content.push_str(&block);
    }

    fs::write(&bashrc, content)?;
    Ok(())
}

pub fn has_ctrl_f_binding() -> io::Result<bool> {
    let home = config::home_dir()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME not set"))?;
    let bashrc = home.join(".bashrc");
    if !bashrc.exists() {
        return Ok(false);
    }
    Ok(find_block_span(&fs::read_to_string(bashrc)?).is_some())
}

fn bind_script_path() -> PathBuf {
    config::config_path()
        .parent()
        .map(|p| p.join("bash-bind.sh"))
        .unwrap_or_else(|| PathBuf::from(".config/tmuxxer/bash-bind.sh"))
}

fn find_block_span(content: &str) -> Option<(usize, usize)> {
    let start = content.find(MARKER_START)?;
    let rest = &content[start..];
    let end_rel = rest.find(MARKER_END)? + MARKER_END.len();
    let end = start + end_rel;
    let end = if content[end..].starts_with('\n') {
        end + 1
    } else {
        end
    };
    Some((start, end))
}
