use std::fs;
use std::io;
use std::path::PathBuf;

use crate::config;
use crate::install;

const MARKER_START: &str = "# >>> tmuxxer >>>";
const MARKER_END: &str = "# <<< tmuxxer <<<";

pub fn install_ctrl_f_binding() -> io::Result<()> {
    let home = config::home_dir()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME not set"))?;
    let bashrc = home.join(".bashrc");
    let bind_script = bind_script_path();

    if let Some(parent) = bind_script.parent() {
        fs::create_dir_all(parent)?;
    }

    let tmuxxer = install::resolve_tmuxxer()?;
    let command = format!(
        "{} sessionize",
        install::shell_quote(&tmuxxer.to_string_lossy())
    );
    fs::write(&bind_script, bind_script_body(&command))?;

    let block = bashrc_block();

    let mut content = if bashrc.exists() {
        fs::read_to_string(&bashrc)?
    } else {
        String::from("# tmuxxer\n")
    };

    if let Some((start, end)) = find_block_span(&content) {
        content.replace_range(start..end, &block);
    } else if !content.ends_with('\n') {
        content.push('\n');
        content.push_str(&block);
    } else {
        content.push_str(&block);
    }

    fs::write(&bashrc, content)?;
    Ok(())
}

fn bind_script_body(command: &str) -> String {
    format!(
        "# Generated by tmuxxer; sourced from ~/.bashrc\n\
case $- in\n\
  *i*) ;;\n\
  *) return 0 2>/dev/null || exit 0 ;;\n\
esac\n\
_tmuxxer_sessionize() {{\n\
  {command}\n\
}}\n\
bind -x '\"\\C-f\": \"_tmuxxer_sessionize\"'\n"
    )
}

fn bashrc_block() -> String {
    format!(
        "{MARKER_START}\n\
if [[ $- == *i* ]]; then\n\
  _tmuxxer_bind=\"${{XDG_CONFIG_HOME:-$HOME/.config}}/tmuxxer/bash-bind.sh\"\n\
  [[ -r \"$_tmuxxer_bind\" ]] && source \"$_tmuxxer_bind\"\n\
  unset _tmuxxer_bind\n\
fi\n\
{MARKER_END}\n"
    )
}

pub fn has_ctrl_f_binding() -> io::Result<bool> {
    let home = config::home_dir()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME not set"))?;
    let bashrc = home.join(".bashrc");
    if !bashrc.exists() {
        return Ok(false);
    }
    Ok(find_block_span(&fs::read_to_string(bashrc)?).is_some())
}

fn bind_script_path() -> PathBuf {
    config::config_path()
        .parent()
        .map(|p| p.join("bash-bind.sh"))
        .unwrap_or_else(|| PathBuf::from(".config/tmuxxer/bash-bind.sh"))
}

fn find_block_span(content: &str) -> Option<(usize, usize)> {
    let start = content.find(MARKER_START)?;
    let rest = &content[start..];
    let end_rel = rest.find(MARKER_END)? + MARKER_END.len();
    let end = start + end_rel;
    let end = if content[end..].starts_with('\n') {
        end + 1
    } else {
        end
    };
    Some((start, end))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bashrc_block_uses_runtime_home_not_install_home() {
        let block = bashrc_block();

        assert!(block.contains("${XDG_CONFIG_HOME:-$HOME/.config}/tmuxxer/bash-bind.sh"));
        assert!(!block.contains("/home/"));
    }

    #[test]
    fn bind_script_runs_inside_and_outside_tmux_without_echoing_command() {
        let script = bind_script_body("'tmuxxer' sessionize");

        assert!(script.contains("_tmuxxer_sessionize()"));
        assert!(script.contains("'tmuxxer' sessionize"));
        assert!(script.contains("bind -x '\"\\C-f\": \"_tmuxxer_sessionize\"'"));
        assert!(!script.contains("TMUX"));
    }
}
