use std::fs;
use std::io;
use std::path::PathBuf;

use crate::config;

const MARKER_START: &str = "# >>> tmuxxer >>>";
const MARKER_END: &str = "# <<< tmuxxer <<<";

pub fn install_ctrl_f_binding() -> io::Result<()> {
    let home = config::home_dir()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME not set"))?;
    let bashrc = home.join(".bashrc");
    let bind_script = bind_script_path();

    if let Some(parent) = bind_script.parent() {
        fs::create_dir_all(parent)?;
    }

    let bind_script_body = "# Generated by tmuxxer; sourced from ~/.bashrc\n\
case $- in\n\
  *i*) ;;\n\
  *) return 0 2>/dev/null || exit 0 ;;\n\
esac\n\
[[ -z ${TMUX:-} ]] || return 0\n\
bind -x '\"\\C-f\": \"tmuxxer sessionize\"'\n";
    fs::write(&bind_script, bind_script_body)?;

    let block = bashrc_block();

    let mut content = if bashrc.exists() {
        fs::read_to_string(&bashrc)?
    } else {
        String::from("# tmuxxer\n")
    };

    if let Some((start, end)) = find_block_span(&content) {
        content.replace_range(start..end, &block);
    } else if !content.ends_with('\n') {
        content.push('\n');
        content.push_str(&block);
    } else {
        content.push_str(&block);
    }

    fs::write(&bashrc, content)?;
    Ok(())
}

fn bashrc_block() -> String {
    format!(
        "{MARKER_START}\n\
if [[ $- == *i* ]]; then\n\
  _tmuxxer_bind=\"${{XDG_CONFIG_HOME:-$HOME/.config}}/tmuxxer/bash-bind.sh\"\n\
  [[ -r \"$_tmuxxer_bind\" ]] && source \"$_tmuxxer_bind\"\n\
  unset _tmuxxer_bind\n\
fi\n\
{MARKER_END}\n"
    )
}

fn bind_script_path() -> PathBuf {
    config::config_path()
        .parent()
        .map(|p| p.join("bash-bind.sh"))
        .unwrap_or_else(|| PathBuf::from(".config/tmuxxer/bash-bind.sh"))
}

fn find_block_span(content: &str) -> Option<(usize, usize)> {
    let start = content.find(MARKER_START)?;
    let rest = &content[start..];
    let end_rel = rest.find(MARKER_END)? + MARKER_END.len();
    let end = start + end_rel;
    let end = if content[end..].starts_with('\n') {
        end + 1
    } else {
        end
    };
    Some((start, end))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bashrc_block_uses_runtime_home_not_install_home() {
        let block = bashrc_block();

        assert!(block.contains("${XDG_CONFIG_HOME:-$HOME/.config}/tmuxxer/bash-bind.sh"));
        assert!(!block.contains("/home/"));
    }
}
