use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SearchRoot {
    pub path: PathBuf,
    pub depth: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Config {
    pub roots: Vec<SearchRoot>,
    pub ignores: Vec<String>,
    pub docker_new_session: bool,
}

impl Config {
    pub fn load() -> io::Result<Self> {
        let path = config_path();
        if !path.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("config not found at {}", path.display()),
            ));
        }
        parse_file(&path)
    }

    pub fn save(&self) -> io::Result<()> {
        save_with_options(&self.roots, &self.ignores, self.docker_new_session)
    }
}

pub fn config_path() -> PathBuf {
    if let Ok(xdg) = env::var("XDG_CONFIG_HOME") {
        PathBuf::from(xdg).join("tmuxxer").join("config")
    } else {
        home_dir()
            .unwrap_or_else(|| PathBuf::from("/"))
            .join(".config")
            .join("tmuxxer")
            .join("config")
    }
}

pub fn exists() -> bool {
    config_path().is_file()
}

pub fn save_with_options(
    roots: &[SearchRoot],
    ignores: &[String],
    docker_new_session: bool,
) -> io::Result<()> {
    save_to_path(&config_path(), roots, ignores, docker_new_session)
}

pub fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME").map(PathBuf::from)
}

fn save_to_path(
    path: &Path,
    roots: &[SearchRoot],
    ignores: &[String],
    docker_new_session: bool,
) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, format_config(roots, ignores, docker_new_session))
}

fn format_config(roots: &[SearchRoot], ignores: &[String], docker_new_session: bool) -> String {
    let mut content = String::from("# Generated by tmuxxer setup\n\n");
    content.push_str(&format!("docker_new_session = {docker_new_session}\n\n"));
    for root in roots {
        content.push_str(&format!("path = {}\n", path_for_config(&root.path)));
        content.push_str(&format!("depth = {}\n\n", root.depth.max(1)));
    }
    for ignore in ignores {
        content.push_str(&format!("ignore = {ignore}\n"));
    }
    content
}

fn parse_file(path: &Path) -> io::Result<Config> {
    parse_content(&fs::read_to_string(path)?)
}

fn parse_content(content: &str) -> io::Result<Config> {
    let mut roots: Vec<SearchRoot> = Vec::new();
    let mut ignores = Vec::new();
    let mut docker_new_session = true;
    let mut default_depth = 1usize;
    let mut last_root = None;

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().to_lowercase();
        let value = value.trim();
        match key.as_str() {
            "path" => {
                roots.push(SearchRoot {
                    path: expand_tilde(value),
                    depth: default_depth,
                });
                last_root = Some(roots.len() - 1);
            }
            "depth" => {
                if let Ok(d) = value.parse::<usize>() {
                    let depth = d.max(1);
                    if let Some(index) = last_root {
                        roots[index].depth = depth;
                    } else {
                        default_depth = depth;
                    }
                }
            }
            "ignore" => {
                if !value.is_empty() && !ignores.iter().any(|ignore| ignore == value) {
                    ignores.push(value.to_string());
                }
            }
            "docker_new_session" => {
                docker_new_session = parse_bool(value).ok_or_else(|| {
                    io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!("invalid {key}: {value} (expected true or false)"),
                    )
                })?;
            }
            _ => {}
        }
    }

    if roots.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "config has no path entries",
        ));
    }

    Ok(Config {
        roots,
        ignores,
        docker_new_session,
    })
}

fn parse_bool(value: &str) -> Option<bool> {
    match value.trim().to_lowercase().as_str() {
        "true" | "yes" | "y" | "1" | "on" => Some(true),
        "false" | "no" | "n" | "0" | "off" => Some(false),
        _ => None,
    }
}

pub fn stored_path(path: &Path) -> String {
    path_for_config(path)
}

pub fn expand_path(home: &Path, input: &str) -> PathBuf {
    if input == "~" {
        return home.to_path_buf();
    }
    if let Some(rest) = input.strip_prefix("~/") {
        return home.join(rest);
    }
    PathBuf::from(input)
}

fn path_for_config(path: &Path) -> String {
    let home = home_dir().unwrap_or_else(|| PathBuf::from("/"));
    if path == home {
        return "~".to_string();
    }
    if let Ok(rest) = path.strip_prefix(&home) {
        let rest = rest.to_string_lossy();
        let rest = rest.strip_prefix('/').unwrap_or(&rest);
        return format!("~/{rest}");
    }
    path.display().to_string()
}

fn expand_tilde(path: &str) -> PathBuf {
    expand_path(&home_dir().unwrap_or_else(|| PathBuf::from("/")), path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn legacy_global_depth_applies_to_all_paths() {
        let config = parse_content(
            "depth = 2\n\
             path = /tmp/code\n\
             path = /tmp/work\n",
        )
        .unwrap();

        assert_eq!(config.roots[0].depth, 2);
        assert_eq!(config.roots[1].depth, 2);
    }

    #[test]
    fn per_path_depth_parses_for_each_path() {
        let config = parse_content(
            "path = /tmp/code\n\
             depth = 1\n\n\
             path = /tmp/work\n\
             depth = 3\n",
        )
        .unwrap();

        assert_eq!(config.roots[0].path, PathBuf::from("/tmp/code"));
        assert_eq!(config.roots[0].depth, 1);
        assert_eq!(config.roots[1].path, PathBuf::from("/tmp/work"));
        assert_eq!(config.roots[1].depth, 3);
    }

    #[test]
    fn docker_new_session_defaults_to_true() {
        let config = parse_content("path = /tmp/code\n").unwrap();

        assert!(config.docker_new_session);
    }

    #[test]
    fn docker_new_session_parses_false() {
        let config = parse_content(
            "docker_new_session = false\n\
             path = /tmp/code\n",
        )
        .unwrap();

        assert!(!config.docker_new_session);
    }

    #[test]
    fn ignores_round_trip_through_save_and_load() {
        let dir = unique_temp_dir("tmuxxer-config");
        let path = dir.join("config");
        let roots = vec![SearchRoot {
            path: dir.join("work"),
            depth: 2,
        }];
        let ignores = vec!["target".to_string(), ".git".to_string()];

        save_to_path(&path, &roots, &ignores, false).unwrap();
        let loaded = parse_file(&path).unwrap();

        assert_eq!(loaded.roots, roots);
        assert_eq!(loaded.ignores, ignores);
        assert!(!loaded.docker_new_session);

        let _ = fs::remove_dir_all(dir);
    }

    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = env::temp_dir().join(format!("{prefix}-{}-{nanos}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        dir
    }
}
